# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 20:36
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import war.apps.wars.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 7, 20, 36, 52, 86502, tzinfo=utc), validators=[war.apps.wars.models.validate_future])),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 7, 20, 37, 52, 86536, tzinfo=utc))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('hashtag', models.CharField(max_length=32)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='battle',
            name='hashtag_left',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_left', to='wars.HashTag'),
        ),
        migrations.AddField(
            model_name='battle',
            name='hashtag_right',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_right', to='wars.HashTag'),
        ),
    ]
