# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 11:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import war.apps.wars.models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 7, 11, 50, 14, 347785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 7, 11, 49, 14, 347751, tzinfo=utc), validators=[war.apps.wars.models.validate_future]),
        ),
    ]
