# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 21:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import war.apps.wars.models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=128)),
                ('num_errors', models.IntegerField(null=True)),
                ('hashtags', models.ManyToManyField(to='wars.HashTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='battle',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 7, 21, 56, 37, 2184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='battle',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 7, 21, 55, 37, 2148, tzinfo=utc), validators=[war.apps.wars.models.validate_future]),
        ),
    ]
