# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 21:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import war.apps.wars.models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0002_auto_20170407_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 7, 21, 56, 52, 353992, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='battle',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 7, 21, 55, 52, 353956, tzinfo=utc), validators=[war.apps.wars.models.validate_future]),
        ),
    ]
