# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 15:56
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc
import war.apps.wars.models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0004_auto_20170408_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 8, 15, 57, 23, 463502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='battle',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 8, 15, 56, 23, 463469, tzinfo=utc), validators=[war.apps.wars.models.validate_future]),
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='tweet',
            name='hashtags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128, null=True), null=True, size=None),
        ),
    ]
